### ISSUE TITLE
ドキュメントの表示領域

### ISSUE THREAD

**Issue by Luzhiled** [luzhiled1333/comp-library#101]
## Description
ドキュメントを開いているブラウザの表示領域の横幅が [900, 960] px の間だと適切な幅にしてくれない

- 8 + 50 + 783 + 50 + 8 = 899px
  - ![899px](https://user-images.githubusercontent.com/20723908/216835341-a2bc6b7b-468e-4d76-b257-ce2c3be57f97.png)
- 8 + 50 + 784 + 50 + 8 = 900 px
  - ![900px](https://user-images.githubusercontent.com/20723908/216835347-7fd86daa-993a-4e9c-835b-e68beb5ffa95.png)
- 8 + 50 + 844 + 50 + 8 = 960px
  - ![960px](https://user-images.githubusercontent.com/20723908/216835356-3c691d92-c220-4539-878d-758d972f9ac1.png)
- 8 + 50 + 845 + 50 + 8 = 961px
  - ![961px](https://user-images.githubusercontent.com/20723908/216835363-6652d32d-789e-44d6-876e-201b082f2b6c.png)

https://github.com/online-judge-tools/verification-helper/blob/75b7b0ffc8bd23237cbf5916bb2986bca2d56ce2/onlinejudge_verify_resources/_includes/theme_fix.html

の min_width を 961 にすると解決する気はする (?)　あんまり調査していない

`.verify-helper/docs/_config.yml` で theme を `jekyll-theme-minimal` 以外に指定するとそもそもこの設定に引っかからないのでそれでも解決するとは思う

## Related files
- `.verify-helper/docs/_config.yml`
- その他

**Comment by Luzhiled** [comment]
これ何で困っているかというと、今使っている環境だと全画面表示で 1920px、左右に等分すると 960px なのでちょうどこの幅に入るんですよね

**Comment by Luzhiled** [comment]
理論値の話をするとテーマの自作という結論になる気がしてきた

**Comment by Luzhiled** [comment]
@ei1333 
これ (https://github.com/luzhiled1333/verification-helper) ってサブコマンドを追加するような実装になっていましたよね？
こっちで修正して https://github.com/luzhiled1333/comp-library/blob/9e852d1710386fe879cec0644f1f1488d52183e1/.github/workflows/verify.yml#L22 とかをいじればうまくいったりするかな

**Comment by ei1333** [comment]
うまくいったりしそうですね

**Comment by Luzhiled** [comment]
治りました　OK
