### ISSUE TITLE
Dijkstra についての様々な変更

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#109]
## Description
- SPFA などに仕様を合わせる
  - 関連 issue, PR
    - #110
    - #113
  - 適切に移動する
  - `class` の名前を変える
  - ドキュメントの計算量の $V$ や $E$ を $|V|$ や $|E|$ に変更する
- `#pragma once` を追加する
- `<vector>`, `<functional>` などの必要なヘッダーを適切に include する

## Related files
- `src/graph/dijkstra.hpp`
- `src/graph/single-source-shortest-path`

**Comment by Luzhiled** [comment]
dijkstra くん問題だらけなので、移動に限らず様々やるべきですね

#pragma once とかもだし、確か vector が使われているのに vector が include されていなかった

**Comment by Luzhiled** [comment]
class の名前も変える必要が

**Comment by ei1333** [comment]
https://github.com/luzhiled1333/comp-library/issues/65#issuecomment-1426393665

**Comment by ei1333** [comment]
`src/graph/single-source-shortest-path/in-weighted-graph.hpp`

**Comment by Luzhiled** [comment]
in-weighted-graph は Floyd-Warshall Algorithm っぽい

**Comment by ei1333** [comment]
そんな

**Comment by Luzhiled** [comment]
いや Floyd-Warshall は APSP だろ　ベルマンフォードです

**Comment by ei1333** [comment]
では、どうしますか

**Comment by Luzhiled** [comment]
正の辺であることをかければいいんじゃないですか

**Comment by ei1333** [comment]
Dijkstraって負辺があると動かないんですね　今知りました

**Comment by Luzhiled** [comment]
負辺があっても動作するが、それは置いておいて positive-weighted とすると

**Comment by ei1333** [comment]
non-negative

**Comment by ei1333** [comment]
負辺があっても動作はするのか

**Comment by Luzhiled** [comment]
6年くらい前にらてくんがポテンシャルの話をしていた記憶があります　詳しいことは全然覚えていません

**Comment by ei1333** [comment]
ところで、SPSAというアルゴリズムはどうでしょう

**Comment by Luzhiled** [comment]
SPFA ではないでしょうか

**Comment by Luzhiled** [comment]
サイレント修正がきていた

**Comment by ei1333** [comment]
サイレント修正しました

**Comment by Luzhiled** [comment]
あ、これ Bellman-Ford より高速になりがちなんですね

**Comment by Luzhiled** [comment]
では issue を立てていただいて

**Comment by Luzhiled** [comment]
まともに読んでないからなんかよくわかんねえけどその手の話っぽいものはいくつか出てきた
https://niuez.hatenablog.com/entry/2019/03/04/142903
https://qiita.com/ngtkana/items/d7fc4463e56b966d1ebf

**Comment by ei1333** [comment]
in-unweighted-graph.hpp、これを解くアルゴリズムが複数あるときに困ることに気が付きました

**Comment by Luzhiled** [comment]
いや、重みなしグラフの最短路は別に1つでよくないですか　他になにか亜種が出てくることありますかね

**Comment by Luzhiled** [comment]
亜種というのは、BFS では原理的に解けないグラフや、特殊なグラフにおいては BFS より真に高速になるようなものという意味ですね

**Comment by ei1333** [comment]
補グラフ最短路というのはどうだろう

**Comment by Luzhiled** [comment]
あーたしかに　まあそれは補グラフの最短路という名前になりそうだけど

**Comment by ei1333** [comment]
あ、これはAPSPでした

**Comment by ei1333** [comment]
特殊なグラフの場合はその名前をつければいいか

**Comment by Luzhiled** [comment]
まあそうなりそうな感じはあるよね

**Comment by Luzhiled** [comment]
Dijkstra は特殊なグラフで高速になる側だと思っていて、命名としてはそうなるのが適切かなと思います

**Comment by Luzhiled** [comment]
in-positive-weighted-graph でいいんじゃないかな

**Comment by Luzhiled** [comment]
ここにきてドキュメントの $|V|$ などが $V$ と表記されていることも発覚してきた

**Comment by ei1333** [comment]
$V$ は頂点集合を指したいですね

**Comment by Luzhiled** [comment]
description を更新しておきました

**Comment by Luzhiled** [comment]
description を更新しておきました3
