### ISSUE TITLE
[graph/single-source-shortest-path] SPFA

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#110]
## Description
Shortest Path Faster Algorithm

## File Name
- `src/single-source-shortest-path/in-weighted-graph.hpp`
- `docs/single-source-shortest-path/in-weighted-graph.hpp`

## TODO
- [ ] 実装
- [ ] ドキュメント作成
- [ ] unit-test
- [ ] verify

## note

- reference material
  - (url)
- implementation
  - (url)
- 関連 issue / PR
  - #109 
- verify:
  - (url)

**Comment by Luzhiled** [comment]
一つの最短路

**Comment by ei1333** [comment]
bellmanfordとSPFA両方必要ですか

**Comment by Luzhiled** [comment]
個人的には SPFA が速いんだから SPFA だけでいいやろという気持ちがあるな　辞典が作りたいわけではないので

**Comment by Luzhiled** [comment]
まあ辞典が作りたいというのもあるな　どうせ盆栽なんだし

**Comment by ei1333** [comment]
もしかしてLuzhiledくんって2人いますか

**Comment by Luzhiled** [comment]
そうだよ

**Comment by Luzhiled** [comment]
そうだよ

**Comment by ei1333** [comment]
実績解除　たまに2回送信される

**Comment by ei1333** [comment]
これ2人いるのか

**Comment by ei1333** [comment]
まあ SPFA が速いので SPFA でいいか functional-graphの遅いやつも消したし

**Comment by Luzhiled** [comment]
done

- #113
