### ISSUE TITLE
[string] ワイルドカードを含むパターンマッチング

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#116]
## Description
$n$ を テキスト文字列の長さ $m$ をパターン文字列の長さとして $O(n \log m)$

## File Name
`src/string/wildcard-pattern-matching.hpp`

## TODO
- [x] 実装
- [x] ドキュメント作成
- [ ] unit-test
- [x] verify

## note

- reference material
  - [ワイルドカードを含むパターンマッチング](https://qiita.com/MatsuTaku/items/cd5581fab97d7e74a7b3)
- implementation
  - (url)
- 関連 issue / PR
  - #
- verify:
  - https://yukicoder.me/problems/no/2231

**Comment by ei1333** [comment]
FFTが必要だが、FFTのライブラリが残念ながら存在しない

**Comment by Luzhiled** [comment]
close していなかったわ
