### ISSUE TITLE
[math] Number theoretic transform

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#117]
## File Name
`src/math/convolution/number-theoretic-transform.hpp`

## TODO
- [ ] 実装
- [ ] ドキュメント作成
- [ ] unit-test
- [ ] verify

## note

- reference material
  - (url)
- implementation
  - (url)
- 関連 issue / PR
  - #
- verify:
  - (url)

**Comment by ei1333** [comment]
#116 で必要

**Comment by Luzhiled** [comment]
`src/math/convolution` ？

**Comment by ei1333** [comment]
math/convolution
math/modular-arithmetic
という説もある

**Comment by Luzhiled** [comment]
やはり tag 機能

**Comment by Luzhiled** [comment]
modular-arithmetic は $O(1)$ 算数の mod 版とかみたいな雰囲気あるよね　全く明文化していないからなんでもいいっちゃいいんだけど

**Comment by ei1333** [comment]
やはりtagか

**Comment by ei1333** [comment]
これは StaticPrimeModInt だと仮定していいのかな
任意modも別に作る必要がありそう

**Comment by ei1333** [comment]
すみません　ドキュメントのパスが間違っていた可能性があります

**Comment by Luzhiled** [comment]
convoltion
