### ISSUE TITLE
clang-formatのバージョン

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#118]
https://github.com/luzhiled1333/comp-library/blob/0a27a6d58556f5a183a4ec3a985447c455269b8d/.github/workflows/format.yml#L19

17 の部分は clang-format のバージョンが更新されて変わる可能性がある

いい感じのコマンドに変えたい

**Comment by ei1333** [comment]
そもそも変わるのがカスというのはある

**Comment by ei1333** [comment]
apt-cache search clangformat-\d+ みたいな感じかな　知らんけど

**Comment by ei1333** [comment]
apt-cache search -n clang-format-[0-9]+ | sort -V -r | sed -n '1{s/^\([^ ]*\).*/\1/p}'　で行けると思っています

**Comment by Luzhiled** [comment]
いいねえ

**Comment by Luzhiled** [comment]
これ何をそれに置き換えたらいいの

**Comment by ei1333** [comment]
clang-format-18の部分ですね

**Comment by Luzhiled** [comment]
うーん　大丈夫そうだし一旦 close するか
