### ISSUE TITLE
[graph/single-source-shortest-path] Distances in Unweighted Graph

### ISSUE THREAD

**Issue by Luzhiled** [luzhiled1333/comp-library#12]
# [graph/single-source-shortest-path] Distances in Unweighted Graph

## file name
`src/graph/single-source-shortest-path/in-unweighted-graph.hpp`

## TODO
- [x] 実装
- [x] ドキュメント作成
- [x] unit-test
- [x] verify

## note
implementation:
- https://atcoder.jp/contests/abc226/submissions/33360204

**Comment by ei1333** [comment]
これは https://github.com/luzhiled1333/comp-library/blob/main/src/graph/distances-on-unweighted-graph.hpp とはちがうものをさしていますか

**Comment by Luzhiled** [comment]
これね　関数渡してあれやこれやというのを考えていたような気もしますね

**Comment by Luzhiled** [comment]
いや、そんなものはさすがに手書きするべきだよな　同じものを指してよさそう

**Comment by Luzhiled** [comment]
implementation にも実質同じものが置かれているし同じものでいいや

docs だけ書いて close しましょう

**Comment by Luzhiled** [comment]
書いていきます

unit-test 必要ですかね

**Comment by ei1333** [comment]
必要か

**Comment by ei1333** [comment]
Distances on weightedも欲しそうと思ったらDijkstraでした

**Comment by Luzhiled** [comment]
これ名前失敗したかな　Unweighted Graph SSSP とかのほうがよかったかもしれない

**Comment by Luzhiled** [comment]
Unweighted Graph Single Source Shortest Path

**Comment by ei1333** [comment]
たしかに

**Comment by Luzhiled** [comment]
SSSP on UG?

**Comment by ei1333** [comment]
ssop ga saisyoni kitahougayosasou

**Comment by Luzhiled** [comment]
確かに

**Comment by Luzhiled** [comment]
というか、sssp でディレクトリを切ったほうがよさそうですね

**Comment by Luzhiled** [comment]
`src/graph/single-source-shortest-path-problem/on-unweighted-graph.hpp` ?

**Comment by Luzhiled** [comment]
on - なんですかね　in - ?

**Comment by ei1333** [comment]
🙆‍♂️

**Comment by Luzhiled** [comment]
in のほうが検索結果が多いな

**Comment by Luzhiled** [comment]
ついでに https://luzhiled1333.github.io/comp-library/src/graph/dijkstra.hpp に設計をあわせようかなと思います

**Comment by Luzhiled** [comment]
5万行くらいになっちゃった

**Comment by ei1333** [comment]
5万行というのは何か方針にミスがあるな　多くても100行くらいではないだろうか

**Comment by Luzhiled** [comment]
fixed #107
