### ISSUE TITLE
トーシェント関数の修正

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#139]
https://github.com/luzhiled1333/comp-library/blob/53179810f22542761a7e657879ebce98b77e3192/src/math/totient-enumeration.hpp#L12-L14

この `n` の方は usize にするべきで、戻り値の型 `T` とは関係がない

**Comment by ei1333** [comment]
と思ったけどそうでもないか？

**Comment by Luzhiled** [comment]
これとは独立して、 header に limits が足りていなさそうですかね？

**Comment by Luzhiled** [comment]
`T` でよさそうな気がする？どうなんだろう
