### ISSUE TITLE
[graph] 強連結成分分解

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#141]
## File Name
`src/graph/decomposition/strongly-connected-components.hpp`

## TODO
- [x] 実装
- [x] ドキュメント作成
- [ ] unit-test
- [x] verify

## note

- reference material
  - (url)
- implementation
  - (url)
- 関連 issue / PR
  - #
- verify:
  - (url)

**Comment by ei1333** [comment]
graph/decomposition/strongly… ？

**Comment by Luzhiled** [comment]
Decomposition of Strongly Connected Components、強連結成分分解とは何が違うんですか

**Comment by ei1333** [comment]
強連結成分分解ですね

**Comment by ei1333** [comment]
日本語が、すみません

**Comment by Luzhiled** [comment]
日本語の妹です。
