### ISSUE TITLE
[graph] Functional Graph 上での jump

### ISSUE THREAD

**Issue by Luzhiled** [luzhiled1333/comp-library#15]
# [graph] Functional Graph 上での jump (オンライン)

## file name
`src/graph/functinal-graph-utility.hpp`

## TODO
- [x] 実装
- [x] ドキュメント作成
- [x] unit-test
- [x] verify

## note
implementation: https://atcoder.jp/contests/abc258/submissions/33414919

# [graph] Functional Graph 上での jump (オフライン)

## file name
`src/graph/offline-query-jump-on-functinal-graph.hpp`

## TODO
- [x] 実装
- [x] ドキュメント作成
- [x] unit-test
- [x] verify

**Comment by Luzhiled** [comment]
あえて

```cpp
void add_edge(from, to, cost)
```

を追加したが、`add_directed_edge` のほうが設計としては統一感があっていいかもしれない

**Comment by Luzhiled** [comment]
Level Ancestor Problem を含むため、$O(1) / query$ を達成しようと思うと Level Ancestor Problem $O(1) / query$ を実装する必要がある

クエリが静的な場合は先読みすることで少しだけ楽に $O(N + Q)$ が達成できる
(参考: https://noshi91.hatenablog.com/entry/2019/09/22/114149)

**Comment by ei1333** [comment]
- #71 
が実装されるとオフラインで $O(N + Q)$ が実装できる

**Comment by ei1333** [comment]
OfflineJumpOnFunctionalGraphQuery?

**Comment by Luzhiled** [comment]
これそうしてもいいかもな　わかるよ

**Comment by ei1333** [comment]
> * [[graph] Level Ancestor #71](https://github.com/luzhiled1333/comp-library/issues/71)
>   が実装されるとオフラインで O(N+Q) が実装できる

書きます　これ

**Comment by Luzhiled** [comment]
functional-graph-utility をやめるか

**Comment by Luzhiled** [comment]
こいつ実装サボって $O(\log |V|) / query$ ができるものを $O(\log k) / query$ にしてんな

**Comment by Luzhiled** [comment]
まあ名前はそうするかな　内部実装が終わっていたので今は https://github.com/luzhiled1333/comp-library/issues/19 と戦っている

**Comment by Luzhiled** [comment]
実装再開！高橋くん

**Comment by Luzhiled** [comment]
いつの日か $O(1) / query$ の Level ancestor が実装されたらまた update しような

**Comment by ei1333** [comment]
高橋くんではなく伊集くんではないか？

**Comment by Luzhiled** [comment]
一旦 done ということで

$O(1)$ Level ancestor が実装されたら reopen するか

**Comment by ei1333** [comment]
辺に重みがある場合に困りました
