### ISSUE TITLE
[math] 素数判定

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#160]
## Description
みらーらびん

## File Name
`src/math/primes/primality-test.hpp`

## TODO
- [ ] 実装
- [ ] ドキュメント作成
- [ ] unit-test
- [ ] verify

## note

- reference material
  - (url)
- implementation
  - (url)
- 関連 issue / PR
  - #155 のために必要
- verify:
  - https://judge.yosupo.jp/problem/primarity_test

**Comment by ei1333** [comment]
64bit対応のprime modintがないことに気づいたので終了です

**Comment by Luzhiled** [comment]
primarity

**Comment by Luzhiled** [comment]
これ本質的に mod_pow だけあればよさそうだしベタ書きしちゃおうかなって

**Comment by ei1333** [comment]
fixed by #188
