### ISSUE TITLE
Dijkstra を Graph を継承する形に書き換える

### ISSUE THREAD

**Issue by Luzhiled** [luzhiled1333/comp-library#17]
## Related files
- `src/graph/dijkstra.hpp`
- `src/graph/graph-template.hpp`
- `docs/graph/dijkstra/hpp`

# 詳細
`graph-template` のメンバをいくつか `protected` に変更したら継承できるようになるはずなので修正する

## メリット
負辺チェックができるようになる

## デメリット
コンストラクタで Dijkstra's Algorithm をしているのをやめる必要があり、初期化し忘れなどが発生するかもしれない
それでサンプルが合うという状況は限られている上、初期化されているかチェックできるはずなのでそこまで大きなものではないと考えている

**Comment by Luzhiled** [comment]
`FunctionalGraph` が `Graph` を継承していることには特に違和感を覚えないんですが、Dijkstra が継承するのはどうなのかなあという気もしてきた

**Comment by ei1333** [comment]
DijkstraはGraphではないだろ

**Comment by Luzhiled** [comment]
しばらく考えたけど、この修正はするべきではないなという結論に至った
