### ISSUE TITLE
[math/modular-arithmetic] enumeration of factorial / inverse of factorial

### ISSUE THREAD

**Issue by Luzhiled** [luzhiled1333/comp-library#20]
# [math/modular-arithmetic] Enumeration of Factorial / Inverse of Factorial

## file name
`src/math/modular-arithmetic/enumeration-of-factorial.hpp`

## TODO
- [x] 実装
- [x] ドキュメント作成
- [ ] unit-test
- [x] verify

## note
- fact / fact_inv の verify:
  - https://atcoder.jp/contests/abc234/submissions/33598954

**Comment by Luzhiled** [comment]
自動で expand するような設計にする

conbination / permutation などは外部関数として実装したほうがいい？
これを渡す必要があるので引数が3つになり、多少面倒かもしれない

**Comment by Luzhiled** [comment]
`FactorialEnumeration` とかにしようかな

**Comment by Luzhiled** [comment]
なんで実装されてないんだよ

**Comment by ei1333** [comment]
これなんで実装されていないんだ？

**Comment by Luzhiled** [comment]
なんでだ？

**Comment by Luzhiled** [comment]
いや、なんで実装されてないんだよ

**Comment by Luzhiled** [comment]
一旦できたということでね
