### ISSUE TITLE
リポジトリの移譲

### ISSUE THREAD

**Issue by Luzhiled** [luzhiled1333/comp-library#26]
しました

壊れている場所がないか確認する (例: README の GitHub Pages へのリンク)

**Comment by ei1333** [comment]
https://github.com/luzhiled1333/comp-library/blob/5d1968a86594b954c1db119b8a10039550cba875/README.md?plain=1#L1-L2

**Comment by ei1333** [comment]
![内包されている場合](https://github.com/Luzhiled/comp-library/blob/main/assets/geometry/Z2/intersect/is-intersect-circle-001.png?raw=true)

**Comment by Luzhiled** [comment]
画像確かに、たすかる

**Comment by Luzhiled** [comment]
GitHub Pages を再生成しないとそもそもダメそうですかね

**Comment by ei1333** [comment]
https://github.com/luzhiled1333/comp-library/blob/5d1968a86594b954c1db119b8a10039550cba875/docs/cpp-template/template.md?plain=1#L13

**Comment by Luzhiled** [comment]
gh-pages に push する必要があるから personal access token で admin:org の権限が新たに必要そうですね
追加しておきます

**Comment by Luzhiled** [comment]
DROPBOX_TOKEN はそのままでいいと思うんですが、なんで落ちているのかはわからない

**Comment by ei1333** [comment]
```
remote: Permission to luzhiled1333/comp-library.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/luzhiled1333/comp-library.git/': The requested URL returned error: 403
Error: failed to verify
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.5/x64/bin/oj-verify", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/onlinejudge_verify/main.py", line 292, in main
    summary = subcommand_run(paths=[], timeout=parsed.timeout, tle=parsed.tle, jobs=parsed.jobs)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/onlinejudge_verify/main.py", line 87, in subcommand_run
    push_timestamp_to_branch()
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/onlinejudge_verify/main.py", line 107, in push_timestamp_to_branch
    subprocess.check_call(['git', 'push', url, 'HEAD'])
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', '***github.com/luzhiled1333/comp-library.git', 'HEAD']' returned non-zero exit status 128.
Error: Process completed with exit code 1.
```

**Comment by ei1333** [comment]
GITHUB TOKENがもつ権限が怪しい

**Comment by Luzhiled** [comment]
admin:org を足してみたんですけど落ちますね

**Comment by ei1333** [comment]
Error:  401 Client Error: Unauthorized for url: https://api.dropboxapi.com/2/files/list_folder

**Comment by Luzhiled** [comment]
これ DROPBOX_TOKEN のアップデートをしたつもりが GH_PAT をアップデートしてたかも(！w)

> admin:org を足してみたんですけど落ちますね

**Comment by Luzhiled** [comment]
DROPBOX_TOKEN のほうは secrets を update してみたら解決した　多分期限切れかなにかだと思う

**Comment by Luzhiled** [comment]
冷静に考えると GH_PAT は GitHub Pages のために使われるはずで、このへんの権限周りがおかしくなっているんだろうな
https://docs.github.com/ja/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by Luzhiled** [comment]
動いた動いた

https://docs.github.com/ja/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
のスコープが移乗とともに「デフォルトアクセス(許可)」から変わったみたいですね

push にはこれ ( https://docs.github.com/ja/rest/git/refs#create-a-reference )が必要そうだったので
https://github.com/luzhiled1333/comp-library/commit/bdf3671a9189812311b331a09abe116dc638f01b で contents に対する permission を追加したら動くようになりました

**Comment by Luzhiled** [comment]
access 権限周りをいじってうしくん追加した

**Comment by ei1333** [comment]
これまだやることあったっけ

**Comment by Luzhiled** [comment]
今のところは変な問題は起きてなさそうだし閉じてもいいかもな
