### ISSUE TITLE
[data-structure] Segment Tree

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#27]
# [data-structure] Segment Tree

## file name
`src/data-structure/segment-tree.hpp`

## TODO
- [x] 実装
- [x] ドキュメント作成
- [x] unit-test
- [x] verify

## note
- https://noshi91.hatenablog.com/entry/2020/04/22/212649 をどうするか？
- 普通のやつ, 双対, 遅延, 二次元などがありどうするか？

**Comment by Luzhiled** [comment]
E のバージョンにする場合は data-structure/segment-tree-utility/ とかにセグ木作って返す関数とかたくさん並べたらいいかなと思ってます

**Comment by ei1333** [comment]
Eにしましょう

**Comment by ei1333** [comment]
E、構造体を書くのが面倒という問題があります

**Comment by Luzhiled** [comment]
> `max_right` と `min_left` はあとで気が向いたら実装します
`value_structure` や `operator_structure` についてもあとで気が向いたら書きます

https://github.com/luzhiled1333/comp-library/pull/68#issuecomment-1409888430

とか言ってるけど、まあええな！

**Comment by ei1333** [comment]
リンクを直してくり

**Comment by ei1333** [comment]
https://alpha3166.github.io/blog/20190414.html

**Comment by Luzhiled** [comment]
https://github.com/luzhiled1333/comp-library/pull/85

直りました

**Comment by Luzhiled** [comment]
冷静に考えると実装していないものや書いていないドキュメントがあるのでしばらく開けておきます

関連: #86 #87

**Comment by Luzhiled** [comment]
いや、別で issue を立てたんだったらいらないか　close します
