### ISSUE TITLE
[sequence] Run Length Encoding

### ISSUE THREAD

**Issue by Luzhiled** [luzhiled1333/comp-library#4]
# [sequence] Run Length Encoding

## file name
`src/sequence/run-length-encoding.hpp`

## TODO
- [x] 実装
- [x] ドキュメント作成
- [ ] unit-test
- [x] verify

## note
- verify with:
  - https://atcoder.jp/contests/abc047/tasks/arc063_a

**Comment by Luzhiled** [comment]
implementation: https://atcoder.jp/contests/abc259/submissions/33225060

**Comment by Luzhiled** [comment]
選択肢として
1. `std::string` だけで実装する
2. `std::vector< std::pair< T, usize > >` で実装する
3. 構造体を定義する

とかがあると思っている

1 は見たことがあるけど普通に意味不明な上に数字が含まれていると一瞬で壊れるのでないかな

3 は名前がつけられて便利だが若干扱いが手間になるかもしれない

**Comment by ei1333** [comment]
1はないな

**Comment by Luzhiled** [comment]
構造体の構造化束縛に対する知識がないので2でいいかな

**Comment by Luzhiled** [comment]
ABC019、古すぎてテストケースが存在せん

**Comment by Luzhiled** [comment]
https://atcoder.jp/contests/typical90/tasks/typical90_cf　これでええかな

**Comment by Luzhiled** [comment]
これもだめやんけ　変なURLやめろ

**Comment by Luzhiled** [comment]
unit test は、ええか！w
