### ISSUE TITLE
Functional Graph の設計

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#48]
## Description
- 以下と同じ理由で、Functional Graph の中に jump の機能があるのは頭ひかりちゃんな気がする
  - https://github.com/luzhiled1333/comp-library/issues/17
  - https://github.com/luzhiled1333/comp-library/issues/42 
-  オンラインクエリに合わせる

 
## Related files
- ` src/graph/functional-graph-utility.hpp`

**Comment by ei1333** [comment]
related https://github.com/luzhiled1333/comp-library/issues/15

**Comment by Luzhiled** [comment]
- #45

**Comment by Luzhiled** [comment]
- `src/graph/class/functional-graph.hpp`
- `src/graph/?/jump-no-file.hpp`
みたいな感じに分けようかなと思っていました　割と賛成です

**Comment by Luzhiled** [comment]
これやるとして、

- undirected / directed
- weighted / unweighted
- general graph / tree / cactus / functional graph / sonota

みたいなもをどこまで作るのかとか考えたほうがよかったりするのかな

**Comment by ei1333** [comment]
例えば木の場合は `graph(?).hpp` を使わずに `tree.hpp` を使う感じですか

**Comment by ei1333** [comment]
思考盗聴　すみません

**Comment by ei1333** [comment]
`functional-graph.hpp` で入次数 1 の assert を入れているので、他もグラフがその条件を満たしているかassertを入れておくと親切そう

**Comment by ei1333** [comment]
flow graphもありますね

**Comment by Luzhiled** [comment]
こっちで議論するのはとっちらかってよくないかな　こっちは close して #45 に統一します
