### ISSUE TITLE
[data-structure] Fenwick Tree

### ISSUE THREAD

**Issue by Luzhiled** [luzhiled1333/comp-library#5]
# [data-structure] Fenwick Tree

**file name**
`src/data-structure/fenwick-tree.hpp`

- [x] 実装
- [x] ドキュメント作成
- [x] unit-test
- [x] verify

**Comment by Luzhiled** [comment]
書いた
https://atcoder.jp/contests/abc234/submissions/33598601

**Comment by Luzhiled** [comment]
msb はさすがに命名を変えようかな

**Comment by ei1333** [comment]
lower_bound、単調増加じゃないといけない（=add(idx,v)のvが全部正) というのもありそう

**Comment by Luzhiled** [comment]
当方オタクなんですけど、全部非負ではないでしょうか

**Comment by Luzhiled** [comment]
コンストラクタ増えたからドキュメントの修正しなきゃいけないじゃん　すいません

**Comment by Luzhiled** [comment]
>  T() で初期化する
これ微妙だな　全要素を `T()` で初期化とかが正確かも

**Comment by ei1333** [comment]
ありがとうございます

**Comment by Luzhiled** [comment]
https://luzhiled1333.github.io/comp-library/src/data-structure/fenwick-tree.hpp

いい感じになったかなと思います
