### ISSUE TITLE
include が足りないファイルがある

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#65]
気になったんですがこのファイルで `#include <vector>` をしていないのって、`graph-template.hpp` で既に `vector` を include しているからですか

_Originally posted by @ei1333 in https://github.com/luzhiled1333/comp-library/pull/60#discussion_r948658225_

**Comment by ei1333** [comment]
インクルードガードがないので何が足りないかよくわからん

**Comment by Luzhiled** [comment]
dijkstra
- vector
- functional

**Comment by ei1333** [comment]
ん、なんでincludeが足りないのに動いているんだ？

**Comment by Luzhiled** [comment]
これ解決したかな　他にはなかった気がするんだけど

**Comment by ei1333** [comment]
なかったか

**Comment by Luzhiled** [comment]
まあ発覚し次第個別で立てていけばいいか
