### ISSUE TITLE
[data-structure] Disjoint Set Union

### ISSUE THREAD

**Issue by Luzhiled** [luzhiled1333/comp-library#7]
# [data-structure] Disjoint Set Union

## file name
`src/data-structure/disjoint-set-union.hpp`

## TODO
- [x] 実装
- [ ] ドキュメント作成
- [ ] unit-test
- [x] verify

## note

**Comment by ei1333** [comment]
groups() 欲しいな

**Comment by Luzhiled** [comment]
確かに

**Comment by Luzhiled** [comment]
`size()`、ac-library と仕様が違うな　どうしよう

**Comment by Luzhiled** [comment]
`group_size(v)` とかを追加しようかなと思うのですがいかがでしょうか

**Comment by ei1333** [comment]
追加しましょう

**Comment by Luzhiled** [comment]
`groups()` や `group_size(v)` を使う問題を募集しております

**Comment by Luzhiled** [comment]
`groups().size()` を返す関数は $O(1)$ で実装できると思うが、ac-library でこれ実装されていないのは何か理由があるのかな

```cpp
DisjointSetUnion d(n);
cnt = n;

x = d.leader(x);
y = d.leader(y);
if (x != y) cnt--;
d.merge(x, y);
```

みたいなことができるのでライブラリ化しなくても問題ないといえば問題ないんですけど

問題例: https://atcoder.jp/contests/abl/tasks/abl_c (1回だけなので `groups.size()` で間に合う)

**Comment by Luzhiled** [comment]
`groups()` も `group_size(v)` も使えそうな問題があった

https://atcoder.jp/contests/abc177/tasks/abc177_d

**Comment by ei1333** [comment]
https://atcoder.jp/contests/abc177/tasks/abc177_d
これ使えませんか

**Comment by ei1333** [comment]
同じ問題でした　すいません

**Comment by Luzhiled** [comment]
https://judge.yosupo.jp/problem/unionfind

これ書いてないの意味不明だな　ドキュメントといっしょにこれ書きます

**Comment by Luzhiled** [comment]
変なケースとか特にないし unit-test は不要な気がする
