### ISSUE TITLE
[math] トーシェント関数

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#75]
## Totient

$\phi(n)$

## File Name
`src/math/totient.hpp`

## TODO
- [x] 実装
- [x] ドキュメント作成
- [x] unit-test
- [x] verify

## note

- implementation
  - (url)
- 関連 issue / PR
  - #
- verify:
  - (url)

## Enumerate Totient

1 以上 n  以下の整数のトーシェント関数の値の列挙

## File Name
`src/math/enumerate-totient.hpp`

1つのファイルにまとめてもいいかも

## TODO
- [x] 実装
- [x] ドキュメント作成
- [x] unit-test
- [x] verify

## note

- implementation
  - (url)
- 関連 issue / PR
  - #
- verify:
  - (url)

**Comment by Luzhiled** [comment]
メモ: $\phi(n)$ の列挙のほうを実装するときはお互いのドキュメントにお互いのドキュメントのことを書くようにする

**Comment by ei1333** [comment]
close
