### ISSUE TITLE
インクルードガード

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#79]
## Description

`#pragma once` を全てのライブラリに書く

## Related files
- `src/*`

**Comment by Luzhiled** [comment]
メモ

`oj-verify docs` を実行すると

```
FILENAME:1:9: warning: #pragma once in main file
    1 | #pragma once
      |         ^~~~
````
みたいなのが大量に出てしまうんですが、これはどうやら gcc のバグっぽくて、 `-fsyntax-only` とかをつけても解決しません

`-w` をつけるとさすがに出なさそうなので、`oj-verify docs` でだけ `-w` をつけるみたいなことができるのであればそうしたい　調査はしていない

**Comment by ei1333** [comment]
しましょう

**Comment by ei1333** [comment]
これおわっているとおもっている
