### ISSUE TITLE
[data-structure] Lazy Segment Tree

### ISSUE THREAD

**Issue by ei1333** [luzhiled1333/comp-library#86]
## File Name
`src/data-structure/segment-tree`

## TODO
- [x] 実装
- [x] ドキュメント作成
- [ ] unit-test
- [x] verify

## note

- implementation
  - (url)
- 関連 issue / PR
  - #
- verify:
  - https://atcoder.jp/contests/abc237/tasks/abc237_g
    - 区間更新 区間sum

**Comment by Luzhiled** [comment]
#27 #87
